.DEFAULT_GOAL := run

install: requirements.txt
    @echo "Installing dependencies..."
    pip install -r requirements.txt

run: install
    @echo "Running the application..."
    python main.py

clean:
    @echo "Cleaning up..."
    find . -type f -name '*.pyc' -delete
    find . -type d -name '__pycache__' -delete

.PHONY: run clean
